# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ImageToAnalyze(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, image_data: str=None, image_url: str=None):  # noqa: E501
        """ImageToAnalyze - a model defined in Swagger

        :param image_data: The image_data of this ImageToAnalyze.  # noqa: E501
        :type image_data: str
        :param image_url: The image_url of this ImageToAnalyze.  # noqa: E501
        :type image_url: str
        """
        self.swagger_types = {
            'image_data': str,
            'image_url': str
        }

        self.attribute_map = {
            'image_data': 'imageData',
            'image_url': 'imageUrl'
        }

        self._image_data = image_data
        self._image_url = image_url

    @classmethod
    def from_dict(cls, dikt) -> 'ImageToAnalyze':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageToAnalyze of this ImageToAnalyze.  # noqa: E501
        :rtype: ImageToAnalyze
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_data(self) -> str:
        """Gets the image_data of this ImageToAnalyze.


        :return: The image_data of this ImageToAnalyze.
        :rtype: str
        """
        return self._image_data

    @image_data.setter
    def image_data(self, image_data: str):
        """Sets the image_data of this ImageToAnalyze.


        :param image_data: The image_data of this ImageToAnalyze.
        :type image_data: str
        """
        if image_data is not None and not re.search(r'^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$', image_data):  # noqa: E501
            raise ValueError("Invalid value for `image_data`, must be a follow pattern or equal to `/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/`")  # noqa: E501

        self._image_data = image_data

    @property
    def image_url(self) -> str:
        """Gets the image_url of this ImageToAnalyze.


        :return: The image_url of this ImageToAnalyze.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this ImageToAnalyze.


        :param image_url: The image_url of this ImageToAnalyze.
        :type image_url: str
        """

        self._image_url = image_url
