---
swagger: "2.0"
info:
  description: "This is the API for nosecount, it processes an image and returns the\
    \ count of persons (humans) on the image. Humans with two noses are counted double\
    \ ;)."
  version: "0.0.2"
  title: "InnT nosecount API"
  contact:
    email: "apiteam@nosecount.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "nosecount.herokuapp.com"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /nosecount:
    post:
      summary: "Post an Image to analyze"
      description: ""
      operationId: "post_image"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Plain image or image as json object"
        required: true
        schema:
          $ref: "#/definitions/ImageToAnalyze"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ImageAnalysis"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  ImageToAnalyze:
    type: "object"
    properties:
      imageData:
        type: "string"
        format: "byte"
        pattern: "^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$"
        x-regex: "^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"
        x-modifiers: []
      imageUrl:
        type: "string"
    example:
      imageData: "imageData"
      imageUrl: "imageUrl"
  ImageAnalysis:
    type: "object"
    properties:
      personCount:
        type: "integer"
        format: "int32"
      accuracy:
        type: "number"
        format: "float"
    example:
      accuracy: 6.0274563
      personCount: 0
